export const access = {
  DASHBOARD: { value: "DASHBOARD", url: "/dashboard" },
  FILE_UPLOAD: { value: "FILE_UPLOAD", url: "/upload" },
  USER: { value: "USER", url: "/users" },
  COURSE_INTRO: { value: "COURSE_INTRO", url: "/course-intro" },
  COURSES: { value: "COURSES", url: "/course" },
  LESSONS_VIDEOS: { value: "LESSONS_VIDEOS", url: "/lesson" },
  DOMAINS_TASKS: { value: "DOMAINS_TASKS", url: "/domains" },
  QUESTIONS: { value: "QUESTIONS", url: "/questions" },
  EXAMS: { value: "EXAMS", url: "/mock-exam" },
  FLASH_CARDS: { value: "FLASH_CARDS", url: "/flashcard" },
  APP_SUPPORT: { value: "APP_SUPPORT", url: "/application-support" },
  EXAM_STRATEGY: { value: "EXAM_STRATEGY", url: "/exam-strategy" },
  CERTIFICATES_PDUS: { value: "CERTIFICATES_PDUS", url: "/generate-certificate" },
  ANNOUNCEMENTS: { value: "ANNOUNCEMENTS", url: "/notifications" },
  NOTIFICATIONS: { value: "NOTIFICATIONS", url: "/notifications" },
  RATING_REVIEWS: { value: "RATING_REVIEWS", url: "/ratings" },
  ROLES: { value: "ROLES", url: "/system-users" },
  COMPANY_PROFILE: { value: "COMPANY_PROFILE", url: "/company-info" },
  SUPPORT: { value: "SUPPORT", url: "" },
  SUBSCRIPTION_MANAGEMENT: { value: "SUBSCRIPTION_MANAGEMENT", url: "/get-plans" },
  SUBSCRIPTION_PURCHASED: { value: "SUBSCRIPTION_PURCHASED", url: "/subscriptions" },
  MOCK_EXAM: { value: "MOCK_EXAM", url: "/mock-exam-results" },
  TICKETS: { value: "TICKETS", url: "/reported-problems" },
  USER_NAVIGATION: { value: "USER_NAVIGATION", url: "/navigations" },
};
